stages:
  - validate
  - plan
  - configure


image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform fmt
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

Deploy-to-EKS:
  image: 
    name: alpine/helm:3.12.3
    entrypoint: [""]
  stage: configure
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip3 install awscli
    - apk update && apk add curl git
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl
    - chmod u+x kubectl && mv kubectl /bin/kubectl
  script:
    - aws eks update-kubeconfig --region us-east-1 --name EKSManish-Thesis-Cluster
    - kubectl create namespace --staging
    - kubectl run pingpong --image=registry.gitlab.com/testman5880607/pingpong-fullstack-multiplayer:latest
