



image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate
  - plan
  - apply
  - configure
  - destroy

variables:
  TF_DIR: ${CI_PROJECT_DIR}
  STATE_NAME: "default"
  ADDRESS: "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${STATE_NAME}"


before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform fmt
  - export GITLAB_ACCESS_TOKEN=$TOKEN
  - cd ${TF_DIR}
  - terraform init -backend-config="address=https://gitlab.com/api/v4/projects/55471835/terraform/state/$TF_STATE_NAME" -backend-config="lock_address=https://gitlab.com/api/v4/projects/55471835/terraform/state/$TF_STATE_NAME/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/55471835/terraform/state/$TF_STATE_NAME/lock" -backend-config="username=Iam-Manishkumar" -backend-config="password=$GITLAB_ACCESS_TOKEN" -backend-config="lock_method=POST" -backend-config="unlock_method=DELETE" -backend-config="retry_wait_min=5"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan      

Deploy-to-EKS:
  image: 
    name: alpine/helm:3.12.3
    entrypoint: [""]
  stage: configure
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip3 install awscli
    - apk update && apk add curl git
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl
    - chmod u+x kubectl && mv kubectl /bin/kubectl
  script:
    - aws eks update-kubeconfig --region us-east-1 --name EKSManish-Thesis-Cluster
    - kubectl create namespace --staging
    - kubectl run pingpong --image=registry.gitlab.com/testman5880607/pingpong-fullstack-multiplayer:latest



destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: always
  dependencies: 
    - apply